### ISSUE TITLE
no Mycommands for forge any more?

### ISSUE THREAD

**Issue by DasFantatier** [Markus23/mycommands#12]
Dear Mod-Maker!

We used mycommands like 2 years ago for forge. Now we have a new server and would like to use it again.
I am a little confused now, because the twitch launcher shows me your mod - and normally it only shows if it is compatible - but it says it´s for fabric.
But we use forge 31.1.0 and MC 1.15.2.

Can you please tell me if i can install this mod normally on my forge server?
And if it is necessary on the clients?

Thank you very much in advice!

**Comment by smmmadden** [comment]
I too am in the same boat.  I really don't want to have to use yet a fifth launcher.  I'm already using Minecraft, Technic and Twitch.  Keeping it on Forge would be good if possible.
