### ISSUE TITLE
Warp doesn't work between dimensions.

### ISSUE THREAD

**Issue by Delubear** [Markus23/mycommands#14]
Using /Warp between dimensions seems to keep you stuck on a loading screen and never actually moves you.  If you close the client and reconnect, you are in your original dimension still.

Ideally this would use a command similar to this:  
/execute in “Dimension Name” run teleport “player name” “location”

**Comment by Delubear** [comment]
Confirmed this is the same behavior with /home as well.

**Comment by wh0oo** [comment]
I can confirm both of the above.  I tested on a freshly made world as well.  its specific to the very latest snapshot.  If you take donations, I would love to donate to this??  This is like the ONLY plugin that works at all, so ...

**Comment by Markus23** [comment]
Warp doesn't work between dimensions. #14 fixed
