### ISSUE TITLE
1.14.2 crash on load fabric loader 1.14.2 - build 2

### ISSUE THREAD

**Issue by SDUBZ** [Markus23/mycommands#3]
fabric 1.14.2- build 2
fabric api: 3.0-170
myc: Mycommands-1.14.2-04

crash report:
[crash-2019-06-02_22.54.48-client.txt](https://github.com/Markus23/mycommands/files/3244829/crash-2019-06-02_22.54.48-client.txt)

logs:
[latest.log](https://github.com/Markus23/mycommands/files/3244830/latest.log)

**Comment by ghost** [comment]
Same problem here. Always seems to be unable to find net.minecraft.network.chat.Component.

Is there an obfuscation problem or is there code that is mistakenly not updated to 1.14?

**Comment by Markus23** [comment]
for me it works. All from 1.14.2-02 - 04
i think is a other mod that crash mycommands

i search

**Comment by XuyuEre** [comment]
same crash again.I only put the `fabric-api-0.3.0+build.175.jar` and `Mycommands-1.14.2-04.jar` in the `mods` ,no other mod.It always crash.
here is the crash files:
[crash-2019-06-02_13.39.27-client.txt](https://github.com/Markus23/mycommands/files/3245022/crash-2019-06-02_13.39.27-client.txt)

logs:
[latest.log](https://github.com/Markus23/mycommands/files/3245023/latest.log)

fabric version:  1.14.2- build 2
fabric loader version: 0.4.8 build 154
fabric api: 3.0-175
myc: Mycommands-1.14.2-04

**Comment by Markus23** [comment]
hi my latest log from original minecraft client

[latest.log](https://github.com/Markus23/mycommands/files/3245138/latest.log)

no crash

**Comment by Markus23** [comment]
fabric version: 1.14.2- build 2
fabric loader version: 0.4.8 build 154
fabric api: 3.0-175
Mycommands-1.14.2-05

that works

**Comment by XuyuEre** [comment]
ok.`Mycommands-1.14.2-05` is no crash .
